# Generated by Django 3.0.3 on 2020-03-10 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_first', models.CharField(max_length=200)),
                ('line_second', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('pincode', models.IntegerField(blank=True, max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(blank=True, max_length=50, null=True)),
                ('hotel_type', models.CharField(choices=[('AC', 'AC'), ('NON-AC', 'NON-AC'), ('AC + NON_AC', 'AC + NON-AC')], max_length=20)),
                ('hotel_Address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sabb.address')),
            ],
        ),
    ]
